version: "3"

services:
  app:
    build: .
    tty: true
    volumes:
      - .:/go/src/work
    ports:
      - "8020:8020"
      - "2345:2345"
    env_file: .envrc    
    working_dir: /go/src/work # loading go file from this path
    command:
      - air
      - -d
    environment:
      - FIREBASEKEY=./secret/serviceAccount.json
      - ENV=LOCAL
      - COLLECTION=DevList
    security_opt: # for delve
      - apparmor:unconfined
    cap_add: # for delve
      - SYS_PTRACE
